### PR TITLE
[FEATURE] Added Feature to use End Date.

### PR DESCRIPTION
**Pull request by yash-rajpal**
### Proposed Changed
Added a new feature for admin to select contributions between a range of dates. Also added a checkBox to enable or disable the end date feature.

### Usage
If the checkbox is disabled, whole project works as it used to work before this PR. If the checkbox is enabled, we can set a custom end date to select contributions between a range of dates.

### Changes made
added endDate to config, to track and date value set by user.
added endDateCheckbox, to track if user has enabled the checkbox or not. The value of this checkbox also shapes the URL's and API calls of github.
If checkbox is disabled everything works as it used to work before. If the checkbox is enabled, the API calls and urls change accordingly. ( created:>=startDate for normal and created:startDate..EndDate for using endDate as well.

### ScreenShots
##Admin Panel
image

## Checkbox enabled and end date set as 15-08-2020
see lolimay's PRs are shown as 35 in that date range, but in total till date he has 42 PRs.
image

## When we disable end Date checkbox
Now it shows total contributions by lolimay till date from start Date.
image

### CODE REVIEW

**Comment by yash-rajpal** [comment]
What do you guys think about this? @Sing-Li @RonLek @djcruz93 @lolimay ?
Thanks.

**Comment by im-adithya** [comment]
What is the use of refresh interval/update when you set an end date?
I think it is better to disable refresh on checking Use End Date as well.

**Comment by yash-rajpal** [comment]
I am sorry @im-adithya I am not able to get your point. 

If you are asking when will the checkbox changes applied to gsoc leaderboard, it will be on next update interval. All api calls after setting this checkbox would include the end date.

**Comment by im-adithya** [comment]
No not that, I mean once you set an end date the data is not going to be changed. So there is no use of _update_ right?

**Comment by yash-rajpal** [comment]
@im-adithya Please refer above comment, I updated it.

**Comment by Sing-Li** [comment]
Sorry @yash-rajpal    There is really no need for end date on this leaderboard.  (and most leaderboards)

I strongly suggest that you first propose with a "Feature Request" before starting to code the next time.    Let the team have a chance to discuss your proposal to avoid wasted effort.

I am going to close this now.

**Comment by yash-rajpal** [comment]
Okay. No problems @Sing-Li , I got learn about the project base and GitHub APIs by working on this, so not all efforts wasted after all. 😃

**Pull request closed without merging**
