### PR TITLE
Adds Dockerfile and publishes ready-to-run image to Docker Hub

### LINKED ISSUE #50: [Feature Request]  Add Dockerfile and publish ready-to-run image
Make this leaderboard a 30 seconds try-it-out decision for those groups already running with dockers or kubernetes.

### PR DESCRIPTION
**Pull request by RonLek**
Closes #50 

Adds Dockerfile for the project and updates README with instructions for deployment.

### CODE REVIEW

**Comment by RonLek** [comment]
@Sing-Li @lolimay @djcruz93 Please review.

**Comment by djcruz93** [comment]
LGTM!

**Review by djcruz93 — APPROVED** [review]

**Review by Sing-Li — CHANGES_REQUESTED** [review]
Great work!    

Please add a docker-compose.yml that:

1) uses the image publish
2) mounts a volume allowing easy modification of configuration file 
3) mounts a volume that stores the data, allowing easy backup of the dashboard data

Thanks.

**Comment by RonLek** [comment]
Thanks @Sing-Li! Added the docker-compose.yml.

**Review by lolimay — APPROVED** [review]

**Pull request merged**
